//@version=3
// Bollinger Bands: Madrid : 14/SEP/2014 11:07 : 2.0
// This displays the traditional Bollinger Bands, the difference is 
// that the 1st and 2nd StdDev are outlined with two colors and two
// different levels, one for each Standard Deviation

study(shorttitle="MBB", title="Bollinger Bands", overlay=true)
src = input(close, type=source)
length = input(34, minval=1)
mult = input(2.0, minval=0.001, maxval=50, type=float)

basis = sma(src, length)
dev = stdev(src, length)
dev2 = mult*dev

upper1 = basis + dev
lower1 = basis - dev
upper2 = basis + dev2
lower2 = basis - dev2

colorBasis = src >= basis ? blue : orange

pBasis = plot(basis, linewidth=2, color=colorBasis)
pUpper1 = plot(upper1, color=blue, style=circles)
pUpper2 = plot(upper2, color=blue)
pLower1 = plot(lower1, color=orange, style=circles)
pLower2 = plot(lower2, color=orange)

fill(pBasis,pUpper2, color=blue, transp=80)
fill(pUpper1, pUpper2, color=blue, transp=80)
fill(pBasis,pLower2, color=orange, transp=80)
fill(pLower1, pLower2, color=orange, transp=80)
