//@version=3
study(title="RSI Highlight", shorttitle="RSI HiLite")
src = hlc3, len = input(14, minval=1, title="Length")
up = rma(max(change(src), 0), len)
down = rma(-min(change(src), 0), len)
rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))
plot(rsi, color=purple)
band1 = hline(70)
band0 = hline(30)
band2 = hline(50,linestyle=dotted,color=silver)
fill(band1, band0, color=#cc99ff, transp=70)
//end premade RSI
oversold = rsi < 30
overbought = rsi > 70
barcolor(oversold? #7fff00 : overbought? red : na )
//
//
level_70 = 70
level_70rsi = rsi > level_70 ? rsi : level_70
level_30 = 30
level_30rsi = rsi < 30 ? rsi : level_30
//


p1 = plot(series=level_70, color=red, linewidth=1, transp=100)
p2 = plot(series=level_70rsi, color=red, linewidth=1, transp=100)
p3 = plot(series=level_30, color=green, linewidth=1, transp=100)
p4 = plot(series=level_30rsi, color=green, linewidth=1, transp=100)
fill(p1, p2, color=red, transp=50)
fill(p3, p4, color=#7fff00, transp=50)
